# Generated by Django 5.1.4 on 2024-12-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='etiquetas',
            field=models.TextField(default='[]'),
        ),
    ]
