# Generated by Django 5.1.4 on 2024-12-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carta_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='etiquetas',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
