# Generated by Django 5.1.4 on 2024-12-16 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_carta_etiquetas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del poema', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido del poema')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('autor', models.ForeignKey(help_text='Usuario que creó el poema', on_delete=django.db.models.deletion.CASCADE, related_name='poemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poema',
                'verbose_name_plural': 'Poemas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
