# Generated by Django 5.1.4 on 2024-12-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_poema'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
